import type { Banner, Category, Product, Coupon, StoreConfig } from "./types";

export const DEFAULT_CONFIG: StoreConfig = {
  storeName: "QuickCart",
  supportPhone: "+91 90000 00000",
  supportEmail: "support@quickcart.com",
  deliveryFee: 2900, // ₹29
  freeDeliveryThreshold: 49900, // ₹499
  platformFee: 500, // ₹5
  minOrderValue: 9900, // ₹99
};

export const SERVICEABLE_PINCODES = [
  "734001",
  "734003",
  "734004",
  "734005",
  "734006",
  "734008",
];

export const CATEGORIES: Category[] = [
  { id: "c1", name: "Fruits & Vegetables", slug: "fruits-vegetables", emoji: "🥦", imageUrl: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=500&auto=format&fit=crop&q=80", sortOrder: 1, isActive: true },
  { id: "c2", name: "Dairy & Eggs", slug: "dairy-eggs", emoji: "🥛", imageUrl: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&auto=format&fit=crop&q=80", sortOrder: 2, isActive: true },
  { id: "c3", name: "Bakery & Breads", slug: "bakery-breads", emoji: "🍞", imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80", sortOrder: 3, isActive: true },
  { id: "c4", name: "Snacks & Beverages", slug: "snacks-beverages", emoji: "🥤", imageUrl: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=500&auto=format&fit=crop&q=80", sortOrder: 4, isActive: true },
  { id: "c5", name: "Household & Cleaning", slug: "household-cleaning", emoji: "🧼", imageUrl: "https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=500&auto=format&fit=crop&q=80", sortOrder: 5, isActive: true },
  { id: "c6", name: "Personal Care", slug: "personal-care", emoji: "🧴", imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500&auto=format&fit=crop&q=80", sortOrder: 6, isActive: true },
  { id: "c7", name: "Frozen Foods", slug: "frozen-foods", emoji: "🧊", imageUrl: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=500&auto=format&fit=crop&q=80", sortOrder: 7, isActive: true },
  { id: "c8", name: "Staples & Grains", slug: "staples-grains", emoji: "🌾", imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80", sortOrder: 8, isActive: true },
];

export const BANNERS: Banner[] = [
  {
    id: "b1",
    title: "10-Minute Delivery",
    subtitle: "Fresh groceries & essentials delivered to your doorstep in Siliguri",
    emoji: "⚡",
    imageUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&auto=format&fit=crop&q=80",
    bg: "from-amber-500 to-orange-600",
    isActive: true,
    sortOrder: 1,
  },
  {
    id: "b2",
    title: "Fresh Farm Veggies",
    subtitle: "Up to 30% OFF on organic fruits & daily greens",
    emoji: "🥦",
    imageUrl: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=800&auto=format&fit=crop&q=80",
    bg: "from-emerald-500 to-teal-700",
    isActive: true,
    sortOrder: 2,
  },
  {
    id: "b3",
    title: "Breakfast Essentials",
    subtitle: "Milk, eggs, bread & butter at wholesale prices",
    emoji: "🍞",
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop&q=80",
    bg: "from-blue-600 to-indigo-800",
    isActive: true,
    sortOrder: 3,
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: "c_welcome20",
    code: "WELCOME20",
    description: "20% off on your first order above ₹299",
    discountType: "PERCENTAGE",
    discountValue: 20,
    minOrderValue: 29900,
    maxDiscount: 10000,
    usedCount: 14,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "c_flat50",
    code: "QUICK50",
    description: "Flat ₹50 off on orders above ₹499",
    discountType: "FLAT",
    discountValue: 5000,
    minOrderValue: 49900,
    usedCount: 28,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Fresh Bananas",
    slug: "fresh-bananas",
    categorySlug: "fruits-vegetables",
    unit: "6 pcs",
    mrp: 6000,
    price: 4900,
    stockQty: 40,
    lowStockThreshold: 5,
    emoji: "🍌",
    imageUrl: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=500&auto=format&fit=crop&q=80",
    tags: ["banana", "fruit"],
    isActive: true,
    isFeatured: true,
    sortOrder: 1,
    description: "Sweet, rich in potassium, naturally ripened fresh bananas.",
  },
  {
    id: "p2",
    name: "Red Apples",
    slug: "red-apples",
    categorySlug: "fruits-vegetables",
    unit: "1 kg",
    mrp: 18000,
    price: 14900,
    stockQty: 25,
    lowStockThreshold: 5,
    emoji: "🍎",
    imageUrl: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=500&auto=format&fit=crop&q=80",
    tags: ["apple", "fruit"],
    isActive: true,
    isFeatured: true,
    sortOrder: 2,
    description: "Crisp and juicy hand-picked red apples from Kinnaur.",
  },
  {
    id: "p3",
    name: "Tomatoes",
    slug: "tomatoes",
    categorySlug: "fruits-vegetables",
    unit: "500 g",
    mrp: 4000,
    price: 2900,
    stockQty: 50,
    lowStockThreshold: 5,
    emoji: "🍅",
    imageUrl: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500&auto=format&fit=crop&q=80",
    tags: ["tomato", "vegetable"],
    isActive: true,
    isFeatured: true,
    sortOrder: 3,
    description: "Farm fresh ripe red tomatoes for salads and cooking.",
  },
  {
    id: "p4",
    name: "Amul Full Cream Milk",
    slug: "amul-full-cream-milk",
    categorySlug: "dairy-eggs",
    unit: "1 L",
    mrp: 7200,
    price: 6800,
    stockQty: 60,
    lowStockThreshold: 10,
    emoji: "🥛",
    imageUrl: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=500&auto=format&fit=crop&q=80",
    brand: "Amul",
    tags: ["milk", "dairy"],
    isActive: true,
    isFeatured: true,
    sortOrder: 4,
    description: "Pasteurized homogenized full cream milk packed with nutrients.",
  },
  {
    id: "p5",
    name: "Farm Eggs",
    slug: "farm-eggs",
    categorySlug: "dairy-eggs",
    unit: "6 pcs",
    mrp: 6500,
    price: 5400,
    stockQty: 30,
    lowStockThreshold: 5,
    emoji: "🥚",
    imageUrl: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=500&auto=format&fit=crop&q=80",
    tags: ["eggs", "protein"],
    isActive: true,
    isFeatured: true,
    sortOrder: 5,
    description: "High-protein farm fresh white eggs.",
  },
  {
    id: "p6",
    name: "Whole Wheat Bread",
    slug: "whole-wheat-bread",
    categorySlug: "bakery-breads",
    unit: "400 g",
    mrp: 5500,
    price: 4500,
    stockQty: 20,
    lowStockThreshold: 4,
    emoji: "🍞",
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80",
    tags: ["bread", "bakery"],
    isActive: true,
    isFeatured: true,
    sortOrder: 6,
    description: "Soft 100% whole wheat fiber-rich sandwich bread.",
  },
  {
    id: "p7",
    name: "Potato Chips Classic",
    slug: "potato-chips-classic",
    categorySlug: "snacks-beverages",
    unit: "90 g",
    mrp: 5000,
    price: 4000,
    stockQty: 45,
    lowStockThreshold: 5,
    emoji: "🥔",
    imageUrl: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop&q=80",
    tags: ["chips", "snack"],
    isActive: true,
    isFeatured: true,
    sortOrder: 7,
    description: "Crispy salted potato chips perfect for tea time.",
  },
  {
    id: "p8",
    name: "Dark Chocolate Bar",
    slug: "dark-chocolate-bar",
    categorySlug: "snacks-beverages",
    unit: "80 g",
    mrp: 15000,
    price: 12500,
    stockQty: 30,
    lowStockThreshold: 5,
    emoji: "🍫",
    imageUrl: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=500&auto=format&fit=crop&q=80",
    tags: ["chocolate", "sweet"],
    isActive: true,
    isFeatured: true,
    sortOrder: 8,
    description: "70% cocoa rich dark chocolate bar.",
  },
];
